### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by jbyttow** [souporserious/react-measure#83]
react-measure is not compatible with React 16 due to its dependency on React.createClass, this should be the only issue, but there may be others...

**Comment by hkelly93** [comment]
@jbyttow I used your suggestion here https://github.com/souporserious/react-measure/pull/86.

Anyone feel free to comment or update my PR.

**Comment by TrySound** [comment]
@jbyttow react-measure does not use React.createClass. And all seems like work fine in my projects.

**Comment by AVickory** [comment]
I believe the issue is specifically that if the Measure component's child is created using createReactClass from the "create-react-class" package then you get the `parameter 1 is not of type "Element"` error thrown here: https://github.com/que-etc/resize-observer-polyfill/blob/master/src/ResizeObserverSPI.js#L81.

**Comment by AVickory** [comment]
nvm just found https://github.com/souporserious/react-measure/issues/76
